/*
 * Copyright 2019 Mek Global Limited
 */

package com.kucoin.futures.core.rest.request;

import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Created by Luka on 2021/3/15
 */
@Data
public class TransferApplyRequest implements Serializable {

    /**
     * A unique ID generated by the user, to ensure the operation is processed by the system only once.
     */
    private String bizNo;

    /**
     * Amount to be transfered out
     */
    private BigDecimal amount;

    /**
     * 币种Currency code
     */
    private String currency;

}
