/*
 * Copyright 2019 Mek Global Limited
 */
package com.kucoin.futures.core.rest.interfaces;

import com.kucoin.futures.core.rest.response.PositionResponse;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.List;

/**
 * Position API
 * @author chenshiwei
 * @since 2019/10/14
 */
public interface PositionAPI {

    /**
     * Get the position details of a specified position.
     *
     * @param symbol Symbol of the contract
     * @return
     * @throws IOException
     */
    PositionResponse getPosition(String symbol) throws IOException;

    /**
     * Get the position details of a specified position.
     *
     * @return
     * @throws IOException
     */
    List<PositionResponse> getPositions() throws IOException;

    /**
     * Enable/Disable of Auto-Deposit Margin
     *
     * @param symbol Symbol of the contract
     * @param status Status
     * @throws IOException
     */
    void setAutoDepositMargin(String symbol, boolean status) throws IOException;

    /**
     * Add Margin Manually
     *
     * @param symbol Ticker symbol of the contract
     * @param margin Margin amount (min. margin amount≥0.00001667XBT）
     * @param bizNo  A unique ID generated by the user, to ensure the operation is processed by the system only once
     * @throws IOException
     */
    void addMarginManually(String symbol, BigDecimal margin, String bizNo) throws IOException;

}
