/*
 * Copyright 2019 Mek Global Limited
 */
package com.kucoin.futures.core.rest.interfaces;

import com.kucoin.futures.core.rest.response.TransferHistory;
import com.kucoin.futures.core.rest.request.DuringPageRequest;
import com.kucoin.futures.core.rest.response.Pagination;
import com.kucoin.futures.core.rest.response.TransferResponse;

import java.io.IOException;
import java.math.BigDecimal;

/**
 * Transfer API
 * @author chenshiwei
 * @email casocroz@gmail.com
 * @date 2019/8/14
 */
public interface TransferAPI {

    /**
     * The amount to be transferred will be deducted from the KuCoin Futures Account.
     * Please ensure that you have sufficient funds in your KuCoin Futures Account, or the transfer will fail.
     * Once the transfer arrives your KuCoin-Main Account, the endpoint will respond and return the applyId.
     * This ID could be used to cancel the transfer request.
     *
     * @param bizNo    A unique ID generated by the user, to ensure the operation is processed by the system only once. You are suggested to use UUID
     * @param amount   Amount to be transfer out
     * @param currency Currency, including XBT,USDT
     * @return response contains applyId
     * @throws IOException
     */
    TransferResponse toKucoinMainAccount(String bizNo, BigDecimal amount, String currency) throws IOException;

    /**
     * Get transfer out request records
     * @param status   [optional] Status PROCESSING, SUCCESS, FAILURE
     * @param currency [optional] Currency, including XBT,USDT
     * @param request  [optional] include startAt endAt currentPage and pageSize parameters  @return
     * @throws IOException
     */
    Pagination<TransferHistory> getTransferOutRecords(String status, String currency, DuringPageRequest request) throws IOException;

    /**
     * Cancel transfer out request
     * The transfer-out request could only be canceled under the “PROCESSING” status.
     * @param applyId
     * @throws IOException
     */
    @Deprecated
    void cancelTransferOutRequest(String applyId) throws IOException;

    /**
     * The amount to be transferred will be deducted from the KuCoin Futures Account.
     * Please ensure that you have sufficient funds in your KuCoin Futures Account, or the transfer will fail.
     * Once the transfer arrives your KuCoin-Main Account, the endpoint will respond and return the applyId.
     * This ID could be used to cancel the transfer request.
     *
     * @param recAccountType Receive account type, including MAIN,TRADE
     * @param amount   Amount to be transfer out
     * @param currency Currency, including XBT,USDT
     * @return
     * @throws IOException
     */
    TransferResponse transferOut(String recAccountType, BigDecimal amount, String currency) throws IOException;

    /**
     * The amount to be transferred will be deducted from the KuCoin Futures Account.
     * Please ensure that you have sufficient funds in your KuCoin Futures Account, or the transfer will fail.
     * Once the transfer arrives your KuCoin-Main Account, the endpoint will respond and return the applyId.
     * This ID could be used to cancel the transfer request.
     *
     * @param payAccountType Payment account type, including MAIN,TRADE
     * @param amount   Amount to be transfer out
     * @param currency Currency, including XBT,USDT
     * @throws IOException
     */
    void transferIn(String payAccountType, BigDecimal amount, String currency) throws IOException;
}
